from datetime import timedelta
from collections import namedtuple

import pandas as pd
from pathlib import Path

RangeFilterType = namedtuple('RangeFilterType', ['min', 'max'])

NATIVE_AREAS = {202: 'FE', 205: 'AEP'}
# NATIVE_AREAS = {202: 'FE', 205: 'AEP', 206: 'OVEC', 209: 'DAY', 212: 'DEOK',
                # 215: 'DUQ', 222: 'CE', 225: 'PJM', 320: 'EKPC', 345: 'DOM'}
BUS_TYPES = {1: 'LOAD', 2: 'GEN', 3: 'SWING', 4: 'SHUTDOWN'}
DEFAULT_KV_FILTER = RangeFilterType(138, 10_000)
GEN_MW_FILTER = RangeFilterType(20, 10_000)
BUS_COL_NAMES = ['I', 'J', 'K', 'IBUS', 'JBUS', 'FROM_BUS', 'TO_BUS', 'W1_BUS', 'W2_BUS', 'W3_BUS']

# Wait this many seconds fo a download to complete.  Useb ys file_util.wait_for_file().
DOWNLOAD_WAIT_SECONDS = 3
RESILIENT = True

INCH_ACTIONS = ('#ADD', '#DELETE', '#MODIFY')
INCH_KEYWORDS = ('Add', 'Modify', 'Mod', 'Delete', 'Del')
INCH_SECTIONS = ('#DATA_TITLE', '#ADD_BUS', '#DELETE_BUS', '#MODIFY_BUS', '#ADD_GEN', '#DELETE_GEN', '#MODIFY_GEN',
                 '#ADD_LOAD', '#DELETE_LOAD', '#MODIFY_LOAD', '#ADD_FXSHUNT', '#DELETE_FXSHUNT', '#MODIFY_FXSHUNT',
                 '#ADD_SWSHUNT', '#DELETE_SWSHUNT', '#MODIFY_SWSHUNT', '#ADD_BRANCH', '#DELETE_BRANCH',
                 '#MODIFY_BRANCH', '#ADD_TRANSFORMER', '#DELETE_TRANSFORMER', '#MODIFY_TRANSFORMER', '#ADD_AREA',
                 '#DELETE_AREA', '#MODIFY_AREA', '#ADD_ZONE', '#DELETE_ZONE', '#MODIFY_ZONE', '#END',
                 )

BUS_INCH_RAW_MAP = {
    "BusNum ‐ ID": "I",
    "BusNumber ‐ Synonymn ‐ ID": "I",
    "BusEMSName": "_",
    "BusNumberChn ‐ Modify ID Data": "_",
    "BusName": "NAME",
    "BusNameExt": "_",
    "BusNomVolt": "BASKV",
    "BusType": "IDE",
    "BusTyp": "_",
    "EIAPlantCode": "_",
    "Gshunt": "_",
    "Bshunt": "_",
    "AreaNum": "AREA",
    "ZoneNum": "ZONE",
    "OwnerNum": "OWNER",
    "VminNorm": "NVLO",
    "VmaxNorm": "NVHI",
    "VminCont": "EVLO",
    "VmaxCont": "EVHI",
    "BusVoltLim": "_",
    "BusVoltLimLow:1": "_",
    "BusVoltLimHigh:1": "_",
    "BusVoltLimLow:2": "_",
    "BusVoltLimHigh:2": "_",
    "BusSlack": "_",
    "LSName": "_",
    "BusMonEle": "_",
    "SubNum": "_",
    "Latitude": "_",
    "LatitudeString": "_",
    "Longitude": "_",
    "LongitudeString": "_",
    "BusVoltPU": "_",
    "BusVoltKV": "VM",
    "BusAngle": "VA",
    "CustomSingle": "_",
    "CustomString": "_",
    "CustomString:1": "_",
    "CustomString:2": "_",
    "CustomString:3": "_",
    "CustomString:4": "_",
    "CustomString:5": "_",
    "UnitName": "_"
}

GENERATOR_INCH_RAW_MAP = {
    "BusNum ‐ ID": "I",
    "BusName": "_",
    "BaseVolt": "_",
    "BusNumberChn ‐ Modify ID": "_",
    "GenID ‐ ID": "ID",
    "unitName ‐ ID": "_",
    "machEquipmentID": "_",
    "Status": "STAT",
    "GenStatus": "_",
    "GenStatusExt": "_",
    "BusNumChn ‐ Modify ID": "_",
    "GenMW": "PG",
    "GenMVR": "QG",
    "GenMWMin": "PB",
    "GenMWMax": "PT",
    "GenMVRMin": "QB",
    "GenMVRMax": "QT",
    "GenRMPCT": "RMPCT",
    "GenRegBusNum": "IREG",
    "CtlBsNam": "_",
    "RegBusBaseVolt": "_",
    "GenVoltSet": "VS",
    "VoltTarg": "_",
    "DZone": "_",
    "MBase": "_",
    "Rsource": "ZR",
    "Xsource": "ZX",
    "RTran": "RT",
    "XTran": "XT",
    "GenTap": "GTAP",
    "GenAGCAble": "_",
    "GenParFac": "_",
    "GenAVRAble": "_",
    "GenUseCapCurve": "_",
    "GenBaseLoadFlag": "_",
    "Own1": "O1",
    "Own2": "O2",
    "Own3": "O3",
    "Own4": "O4",
    "CustomString": "_",
    "CustomString:1": "_",
    "CustomString:2": "_",
    "CustomString:3": "_",
    "CustomString:4": "_"
}

LOAD_INCH_RAW_MAP = {
    "BusName": "I",
    "BaseVolt": "_",
    "BusNumberChn ‐ Modify ID": "_",
    "LoadID ‐ ID": "ID",
    "Status": "STATUS",
    "StatusOpCl": "_",
    "ConfrmFlag": "_",
    "LoadP0": "PL",
    "LoadQ0": "QL",
    "LoadP1": "IP",
    "LoadQ1": "IQ",
    "LoadP2": "YP",
    "LoadQ2": "YQ",
    "CustomString": "_",
    "CustomString:1": "_",
    "CustomSingle": "_",
    "CustomSingle:1": "_",
    "LoadArea": "AREA",
    "LoadZone": "ZONE",
    "LoadOwner": "OWNER",
    "LoadType": "_"
}

SWITCHED_SHUNT_INCH_RAW_MAP = {
    "BusNum ‐ ID": "_",
    "ShuntID ‐ ID": "_",
    "BusName": "_",
    "Mode": "_",
    "BlockOrder": "_",
    "Status": "_",
    "VMin": "_",
    "VMax": "_",
    "BShuntCur": "_",
    "RemPcnt": "_",
    "CtlBs#": "_",
    "ModDescr": "_",
    "BShuntMin": "_",
    "BShuntMax": "_",
    "CtlBsNam": "_",
    "NomV": "_",
    "BankStatus1": "_",
    "NBank1": "_",
    "BankSize1": "_",
    "BankStatus2": "_",
    "NBank2": "_",
    "BankSize2": "_",
    "BankStatus3": "_",
    "NBank3": "_",
    "BankSize3": "_",
    "BankStatus4": "_",
    "NBank4": "_",
    "BankSize4": "_",
    "BankStatus5": "_",
    "NBank5": "_",
    "BankSize5": "_",
    "BankStatus6": "_",
    "NBank6": "_",
    "BankSize6": "_",
    "BankStatus7": "_",
    "NBank7": "_",
    "BankSize7": "_",
    "BankStatus8": "_",
    "NBank8": "_",
    "BankSize8": "_",
    "BankStatus9": "_",
    "NBank9": "_",
    "BankSize9": "_",
    "BankStatus10": "_",
    "NBank10": "_",
    "BankSize10": "_",
    "BankStatus11": "_",
    "NBank11": "_",
    "BankSize11": "_",
    "BankStatus12": "_",
    "NBank12": "_",
    "BankSize12": "_"
}

BRANCH_INCH_RAW_MAP = {
    "BusNumFr ‐ ID": "_",
    "busNamFr": "_",
    "BusVoltFr": "_",
    "BusNumTo ‐ ID": "_",
    "busNamTo": "_",
    "BusVoltTo": "_",
    "CKT ‐ ID": "_",
    "Status": "_",
    "Mt": "_",
    "LineR": "_",
    "LineX": "_",
    "Charge": "_",
    "ShuntGFr": "_",
    "ShuntBFr": "_",
    "ShuntGTo": "_",
    "ShuntBTo": "_",
    "Length": "_",
    "RateA": "_",
    "RateB": "_",
    "RateC": "_",
    "RateD": "_",
    "Rate1": "_",
    "Rate2": "_",
    "Rate3": "_",
    "Rate4": "_",
    "Rate5": "_",
    "Rate6": "_",
    "Rate7": "_",
    "Rate8": "_",
    "Rate9": "_",
    "Rate10": "_",
    "Rate11": "_",
    "Rate12": "_",
    "Rate13": "_",
    "Rate14": "_",
    "Rate15": "_",
    "Rate16": "_",
    "BranchName": "_",
    "Own1": "_",
    "Own2": "_",
    "Own3": "_",
    "Own4": "_",
    "CustomString": "_",
    "CustomString:1": "_",
    "CustomString:2": "_"
}

TRANSFORMER_INCH_RAW_MAP = {
    "W1Bus# ‐ ID": "W1Bus# ‐ ID",
    "W2Bus# ‐ ID": "W2Bus# ‐ ID",
    "W3Bus# ‐ ID": "W3Bus# ‐ ID",
    "W1Name": "W1Name",
    "W2Name": "W2Name",
    "W3Name": "W3Name",
    "W1Volt": "W1Volt",
    "W2Volt": "W2Volt",
    "W3Volt": "W3Volt",
    "CKT ‐ ID": "CKT ‐ ID",
    "XfmrName": "XfmrName",
    "BranchName": "BranchName",
    "Status": "Status",
    "CW": "CW",
    "CZ": "CZ",
    "CM": "CM",
    "MAG1": "MAG1",
    "MAG2": "MAG2",
    "MtBus": "MtBus",
    "R1‐2": "R1‐2",
    "X1‐2": "X1‐2",
    "SBAS1": "SBAS1",
    "R2‐3": "R2‐3",
    "X2‐3": "X2‐3",
    "SBAS2": "SBAS2",
    "R3‐1": "R3‐1",
    "X3‐1": "X3‐1",
    "SBAS3": "SBAS3",
    "Own1": "Own1",
    "Own2": "Own2",
    "Own3": "Own3",
    "Own4": "Own4",
    "W1WINV": "W1WINV",
    "W1NOMV": "W1NOMV",
    "W1ANG": "W1ANG",
    "W1Status": "W1Status",
    "W1AdjStatus": "W1AdjStatus",
    "W1 CtrlBus": "W1 CtrlBus",
    "W1RegulMin": "W1RegulMin",
    "W1RegulMax": "W1RegulMax",
    "W1TargetMin": "W1TargetMin",
    "W1TargetMax": "W1TargetMax",
    "W1NumTapPos": "W1NumTapPos",
    "W1NTable": "W1NTable",
    "W1LDropR": "W1LDropR",
    "W1LDropX": "W1LDropX",
    "W2WINV": "W2WINV",
    "W2NOMV": "W2NOMV",
    "W2ANG": "W2ANG",
    "W2Status": "W2Status",
    "W2AdjStatus": "W2AdjStatus",
    "W2CtrlBus": "W2CtrlBus",
    "W2RegulMin": "W2RegulMin",
    "W2RegulMax": "W2RegulMax",
    "W2TargetMin": "W2TargetMin",
    "W2TargetMax": "W2TargetMax",
    "W2NumTapPos": "W2NumTapPos",
    "W2NTable": "W2NTable",
    "W2LDropR": "W2LDropR",
    "W2LDropX": "W2LDropX",
    "W3WINV": "W3WINV",
    "W3NOMV": "W3NOMV",
    "W3ANG": "W3ANG",
    "W3Status": "W3Status",
    "W3AdjStatus": "W3AdjStatus",
    "W3CtrlBus": "W3CtrlBus",
    "W3RegulMin": "W3RegulMin",
    "W3RegulMax": "W3RegulMax",
    "W3TargetMin": "W3TargetMin",
    "W3TargetMax": "W3TargetMax",
    "W3NumTapPos": "W3NumTapPos",
    "W3NTable": "W3NTable",
    "W3LDropR": "W3LDropR",
    "W3LDropX": "W3LDropX",
    "Unknown": "Unknown",
    "VMStar": "VMStar",
    "ANStar": "ANStar",
    "W1RateA": "W1RateA",
    "W1RateB": "W1RateB",
    "W1RateC": "W1RateC",
    "W2RateA": "W2RateA",
    "W2RateB": "W2RateB",
    "W2RateC": "W2RateC",
    "W3RateA": "W3RateA",
    "W3RateB": "W3RateB",
    "W3RateC": "W3RateC",
    "W1Rate1": "W1Rate1",
    "W1Rate2": "W1Rate2",
    "W1Rate3": "W1Rate3",
    "W1Rate4": "W1Rate4",
    "W1Rate5": "W1Rate5",
    "W1Rate6": "W1Rate6",
    "W1Rate7": "W1Rate7",
    "W1Rate8": "W1Rate8",
    "W1Rate9": "W1Rate9",
    "W1Rate10": "W1Rate10",
    "W1Rate11": "W1Rate11",
    "W1Rate12": "W1Rate12",
    "W1Rate13": "W1Rate13",
    "W1Rate14": "W1Rate14",
    "W1Rate15": "W1Rate15",
    "W1Rate16": "W1Rate16",
    "W2Rate1": "W2Rate1",
    "W2Rate2": "W2Rate2",
    "W2Rate3": "W2Rate3",
    "W2Rate4": "W2Rate4",
    "W2Rate5": "W2Rate5",
    "W2Rate6": "W2Rate6",
    "W2Rate7": "W2Rate7",
    "W2Rate8": "W2Rate8",
    "W2Rate9": "W2Rate9",
    "W2Rate10": "W2Rate10",
    "W2Rate11": "W2Rate11",
    "W2Rate12": "W2Rate12",
    "W2Rate13": "W2Rate13",
    "W2Rate14": "W2Rate14",
    "W2Rate15": "W2Rate15",
    "W2Rate16": "W2Rate16",
    "W3Rate1": "W3Rate1",
    "W3Rate2": "W3Rate2",
    "W3Rate3": "W3Rate3",
    "W3Rate4": "W3Rate4",
    "W3Rate5": "W3Rate5",
    "W3Rate6": "W3Rate6",
    "W3Rate7": "W3Rate7",
    "W3Rate8": "W3Rate8",
    "W3Rate9": "W3Rate9",
    "W3Rate10": "W3Rate10",
    "W3Rate11": "W3Rate11",
    "W3Rate12": "W3Rate12",
    "W3Rate13": "W3Rate13",
    "W3Rate14": "W3Rate14",
    "W3Rate15": "W3Rate15",
    "W3Rate16": "W3Rate16",

}

AREA_INCH_RAW_MAP = {
    "AreaNum ‐ ID": "AreaNum ‐ ID",
    "AreaName": "AreaName",
    "DesInter": "DesInter",
    "SlackBusNum": "SlackBusNum",
    "AreaNumTo": "AreaNumTo",
    "AreaNumChn": "AreaNumChn",
    "ZoneNum": "ZoneNum"
}

ZONE_INCH_RAW_MAP = {
    "ZoneNum ‐ ID": "ZoneNum ‐ ID",
    "ZoneName": "ZoneName",
    "ZoneNumTo": "ZoneNumTo",
    "ZoneNumChn": "ZoneNumChn",
    "AreaNum": "AreaNum"
}



